name = "FdeSolver"
uuid = "1746e360-1058-44a5-9855-ddd460437d0c"
authors = ["Moein Khalighi", "Giulio Benedetti"]
version = "0.2.1"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
FFTW = "1.4"
LinearAlgebra = "1.0"
SpecialFunctions = "1.0"
julia = "1.4 - 1.6.3"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"

[targets]
examples = ["Plots"]
test = ["Test", "SafeTestsets", "Statistics"]
benchmark = ["BenchmarkTools"]
